/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-03-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-03-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class checkRecursive {
    private static boolean run = false;
}