public class JWTIntegration {
    
    public void requestAccessToken(){
         
                
    }
    public class Header{
        string arg;
        Header(string alg){
            this.arg=arg;            
        }        
    }
    public class Body{
        string iss;
        string prn;
        string aud;
        string exp;
        Body(string iss,string prn,string aud,string exp){
            this.iss=iss;
            this.prn=prn;
            this.aud=aud;
            this.exp=exp;
        }      
    } 
    public class JwtException extends Exception{
        
        
        
        
        
        
    }      
}